// ABOUTME: Config-driven description of one map lump (from the maplumpnames block): which lumps make up a map and how.
// ABOUTME: Drives format-correct save-back - what to copy blindly, what the node builder regenerates, what is required.

namespace DBuilder.IO;

/// <summary>
/// Properties of a single map lump. The marker placeholder is named "~MAP". <see cref="NodeBuild"/> lumps are
/// regenerated by the node builder; <see cref="BlindCopy"/> lumps (BEHAVIOR, ~MAP) are preserved verbatim.
/// </summary>
public sealed class MapLumpInfo
{
    public string Name { get; init; } = "";
    public bool Required { get; init; }
    public bool BlindCopy { get; init; }
    public bool NodeBuild { get; init; }
    public bool AllowEmpty { get; init; }
    public bool Forbidden { get; init; }
    /// <summary>Script-config filename for text script lumps (e.g. SCRIPTS), or null.</summary>
    public string? Script { get; init; }

    /// <summary>True for the map marker placeholder lump ("~MAP").</summary>
    public bool IsMarker => Name == "~MAP";
}
