// ABOUTME: Documents the DBuilder renderer replacement contract for UDB native OpenGL pieces.
// ABOUTME: Keeps renderer architecture status testable while full render parity is still in progress.

namespace DBuilder.Rendering;

public sealed record RendererArchitectureReplacement(
    string DeviceApi,
    string ShaderCompilerStrategy,
    string ShaderManagerReplacement,
    string MinimumGlProfile,
    IReadOnlyList<string> CoveredResponsibilities,
    IReadOnlyList<string> RemainingGaps);

public sealed record Renderer2DContractSurface(
    IReadOnlyList<string> Properties,
    IReadOnlyList<string> Methods);

public static class RendererArchitectureModel
{
    public static Renderer2DContractSurface Renderer2DContract { get; } = new(
        Properties: new[]
        {
            "float OffsetX",
            "float OffsetY",
            "float TranslateX",
            "float TranslateY",
            "float Scale",
            "int VertexSize",
            "bool DrawMapCenter",
            "ViewMode ViewMode",
        },
        Methods: new[]
        {
            "Vector2D DisplayToMap(Vector2D mousepos)",
            "Vector2D MapToDisplay(Vector2D mappos)",
            "PixelColor DetermineLinedefColor(Linedef l)",
            "PixelColor DetermineThingColor(Thing t)",
            "int DetermineVertexColor(Vertex v)",
            "int CalculateBrightness(int level)",
            "void UpdateExtraFloorFlag()",
            "bool StartPlotter(bool clear)",
            "bool StartThings(bool clear)",
            "bool StartOverlay(bool clear, int layernum = 0)",
            "void Finish()",
            "void SetPresentation(Presentation present)",
            "void Present()",
            "void PlotLine(Vector2D start, Vector2D end, PixelColor c)",
            "void PlotLine(Vector2D start, Vector2D end, PixelColor c, float lengthscaler)",
            "void PlotLinedef(Linedef l, PixelColor c)",
            "void PlotLinedefSet(ICollection<Linedef> linedefs)",
            "void PlotSector(Sector s)",
            "void PlotSector(Sector s, PixelColor c)",
            "void PlotVertex(Vertex v, int colorindex, bool checkMode = true)",
            "void PlotVertexAt(Vector2D v, int colorindex, bool checkMode = true)",
            "void PlotVerticesSet(ICollection<Vertex> vertices, bool checkMode = true)",
            "void RenderThing(Thing t, PixelColor c, float alpha)",
            "void RenderThingSet(ICollection<Thing> things, float alpha)",
            "void RenderThingSet(ICollection<Thing> things, PixelColor c, float alpha)",
            "void RenderRectangle(RectangleF rect, float bordersize, PixelColor c, bool transformrect)",
            "void RenderRectangleFilled(RectangleF rect, PixelColor c, bool transformrect)",
            "void RenderRectangleFilled(RectangleF rect, PixelColor c, bool transformrect, ImageData texture)",
            "void RenderLine(Vector2D start, Vector2D end, float thickness, PixelColor c, bool transformcoords)",
            "void RenderArrows(ICollection<Line3D> line)",
            "void RenderArrows(ICollection<Line3D> line, bool transformcoords)",
            "void RenderText(TextLabel text)",
            "void RenderText(ITextLabel text)",
            "void RenderText(IList<ITextLabel> labels)",
            "void RenderGeometry(FlatVertex[] vertices, ImageData texture, bool transformcoords)",
            "void RenderHighlight(FlatVertex[] vertices, int color)",
            "void RedrawSurface()",
        });

    public static RendererArchitectureReplacement Current { get; } = new(
        DeviceApi: "Silk.NET OpenGL through Avalonia GL contexts and standalone Silk window hosts",
        ShaderCompilerStrategy: "Runtime GLSL compilation through DBuilder.Rendering.Shader",
        ShaderManagerReplacement: "Direct Shader instances with uniform-location caching replace UDB GLShader and GLShaderManager for the current renderer subset",
        MinimumGlProfile: "Desktop OpenGL 3.3 core profile",
        CoveredResponsibilities: new[]
        {
            "Viewport and clear state",
            "Render-device viewport planning",
            "Render-device disposed-state reporting",
            "2D presentation layer stack planning",
            "2D presentation draw-command planning",
            "2D presentation blend-factor application planning",
            "2D presentation render-target lifecycle planning",
            "2D presentation plotter and texture target allocation planning",
            "2D presentation display shader settings planning",
            "2D presentation display uniform application planning",
            "2D presentation display render-settings vector planning",
            "2D presentation projection transform planning",
            "2D presentation frame operation sequence planning",
            "2D presentation frame setup and release binding planning",
            "2D presentation render-layer mask planning",
            "2D presentation set-presentation overlay lifecycle planning",
            "2D presentation render-target transform reset and redraw planning",
            "2D presentation renderer lifecycle operation planning",
            "2D presentation render-target destroy sequence planning",
            "2D presentation render-target create sequence planning",
            "2D presentation render-target dimension validation planning",
            "2D presentation background draw availability planning",
            "2D presentation background vertex-buffer restore planning",
            "2D presentation layer draw dispatch argument planning",
            "2D presentation layer texture binding planning",
            "2D presentation per-layer draw operation sequence planning",
            "2D presentation planner input validation planning",
            "2D presentation render-session start and finish planning",
            "2D presentation surface redraw operation planning",
            "Renderer2D contract surface model",
            "Renderer2D coordinate transform planning",
            "Renderer2D color selection planning",
            "Renderer2D brightness color planning",
            "Renderer2D extra-floor flag planning",
            "Renderer2D sector plotting operation planning",
            "Renderer2D vertex set plotting planning",
            "Render-device alpha-blend state planning",
            "Render-device alpha-test compatibility state planning",
            "Render-device multisample antialias compatibility state planning",
            "Render-device depth and depth-write state planning",
            "Render-device blend-operation planning",
            "Render-device blend-factor planning",
            "Render-device cull and fill raster-state planning",
            "Render-device sampler-filter overload planning",
            "Render-device sampler address-state planning",
            "Render-device setup settings planning",
            "Render-device setup settings state application",
            "Render-device resource registration lifecycle planning",
            "Render-device target start-rendering planning",
            "Render-device Color4 start-rendering overload planning",
            "Render-device inline vertex draw planning and overload",
            "Render-device draw plan input validation planning",
            "Render-device finish and present frame handoff planning",
            "Render-device named shader and uniform operation planning",
            "Render-device named shader and uniform source-compatible method surface",
            "Render-device named uniform payload conversion planning",
            "Render-device uniform array input validation planning",
            "Render-device constructor input validation planning",
            "Cull, depth, fill, blend, sampler, and texture state",
            "VertexFormat enum surface",
            "Flat and world vertex-buffer attribute binding",
            "Vertex and index buffer binding planning",
            "Render-device vertex and index buffer binding state reporting",
            "Vertex and index buffer constructor input validation planning",
            "Length-based vertex-buffer allocation",
            "Flat and world vertex-buffer subdata updates",
            "Index-buffer subdata updates",
            "Vertex and index buffer upload byte-size planning",
            "Render-device array upload input validation planning",
            "Vertex and index buffer disposed-state reporting",
            "Length-based index-buffer allocation",
            "Index-buffer finalizer lifecycle",
            "Index-buffer binding and primitive draw dispatch",
            "Texture disposed-state reporting",
            "Base texture lifecycle and render-device binding surface",
            "Texture constructor input validation planning",
            "Texture format metadata and 2D/cube allocation planning",
            "Texture allocation validation planning",
            "Texture 2D format allocation application",
            "Texture pixel upload byte-size planning",
            "Render-device texture operation planning",
            "Render-device Color4 texture clear overload planning",
            "Render-device 2D texture clear and pixel upload application",
            "Render-device texture pixel upload byte-size planning",
            "Render-device unsafe plotter pixel upload surface",
            "Cube texture resource and render-device cube operation surface",
            "Cube texture render-device constructor surface",
            "Cube map face enum values",
            "ColorSetting helper surface",
            "PixelColor conversion and channel alias surface",
            "ColorCollection default and mutable array surface",
            "PixelColor arithmetic helper surface",
            "Owned indexed-triangle mesh wrapper",
            "Mesh construction, draw, and dispose operation planning",
            "Mesh disposal and finalizer lifecycle",
            "Mesh disposed-state reporting",
            "Mesh constructor input validation planning",
            "Mesh primitive-count validation planning",
            "Mesh draw availability planning",
            "Surface-entry chunk metadata and bounds model",
            "Surface buffer set field carrier",
            "Surface manager vertex chunk and buffer allocation planning",
            "Surface buffer entry-size validation planning",
            "Surface buffer hole allocation and free-entry planning",
            "Surface update entry application and chunk reuse planning",
            "Surface update vertex-count validation planning",
            "Surface render pass visibility filtering and texture grouping",
            "Surface render pass validation planning",
            "Surface render texture fallback resolution planning",
            "Surface render draw-command and vertex-buffer binding planning",
            "Surface render invalid-entry command filtering planning",
            "Surface render shader and sampler state planning",
            "Surface buffer resource reload upload planning",
            "Surface buffer reset invalidation planning",
            "Surface buffer unload and reload resource-state planning",
            "Surface locked-buffer unlock lifecycle planning",
            "Surface manager resource registration and lifecycle planning",
            "Surface manager map-analysis allocation planning",
            "Surface manager update buffer upload planning",
            "Surface manager update and free surface-entry lifecycle planning",
            "Text font byte-indexed glyph table planning",
            "Text font Font.cfg resource discovery and glyph-source parsing",
            "Text font resource and containment helpers",
            "Text font configuration metric normalization",
            "Text font glyph metrics and vertex planning",
            "Text font string vertex sequence planning",
            "Text label constructor and dispose lifecycle planning",
            "Text label font selection and legacy scale planning",
            "Text label compatibility property mutation planning",
            "Text label UDB setter invalidation planning",
            "Text label scale setter font invalidation planning",
            "Text label size, alignment, transform, culling, and quad planning",
            "Text label plain and background image drawing planning",
            "Text label skipped-label filtering and render dispatch planning",
            "Text label render dispatch planning",
            "Text label render-state planning",
            "Text label planner input validation planning",
            "Text label dirty-state and resource invalidation planning",
            "Text label unload-resource disposal planning",
            "Text label transform-cache invalidation planning",
            "Text label skipped-resource invalidation planning",
            "Text label skipped-resource invalidation distinction",
            "Text label offscreen texture disposal planning",
            "Text label offscreen vertex-buffer disposal planning",
            "Text label texture and vertex-buffer update planning",
            "Text label texture upload reuse planning",
            "Text label missing-texture recovery planning",
            "Text label viewport inclusion planning",
            "Runtime shader compile, link, disposal, and uniform lookup caching",
            "Shader disposed-state reporting",
            "Shader constructor input validation planning",
        },
        RemainingGaps: new[]
        {
            "Full UDB render-pass graph",
            "Live surface manager GL execution",
            "Full mesh behavior",
            "Live text font texture generation and GL execution",
            "Complete visual-mode rendering parity",
        });

    public static string Summary(RendererArchitectureReplacement replacement)
        => $"{replacement.DeviceApi}; shaders: {replacement.ShaderCompilerStrategy}; manager: {replacement.ShaderManagerReplacement}.";

    public static bool HasDocumentedShaderCompilerReplacement(RendererArchitectureReplacement replacement)
        => replacement.ShaderCompilerStrategy.Contains("Runtime GLSL", StringComparison.Ordinal)
            && replacement.ShaderCompilerStrategy.Contains(nameof(Shader), StringComparison.Ordinal)
            && replacement.ShaderManagerReplacement.Contains("GLShaderManager", StringComparison.Ordinal);
}
